"""empty message

Revision ID: 52b9eb053a78
Revises: ecacbc24e19a
Create Date: 2020-04-30 18:08:30.601958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b9eb053a78'
down_revision = 'ecacbc24e19a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pandemic_whistles', 'test_anti_neg',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pandemic_whistles', 'test_anti_pos',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pandemic_whistles', 'test_swab_neg',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pandemic_whistles', 'test_swab_pos',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pandemic_whistles', 'test_swab_pos',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pandemic_whistles', 'test_swab_neg',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pandemic_whistles', 'test_anti_pos',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pandemic_whistles', 'test_anti_neg',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
