"""empty message

Revision ID: 9b43a553ea1f
Revises: c929b4d8fe16
Create Date: 2018-03-30 15:23:07.229415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b43a553ea1f'
down_revision = 'c929b4d8fe16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zips',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('zip', sa.String(length=6), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('district', sa.String(length=2), nullable=False),
    sa.Column('factor', sa.Float(precision=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zips_zip'), 'zips', ['zip'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zips_zip'), table_name='zips')
    op.drop_table('zips')
    # ### end Alembic commands ###
