"""empty message

Revision ID: bde2607caa38
Revises: 25009d06c1c5
Create Date: 2020-04-18 08:25:29.437536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = 'bde2607caa38'
down_revision = '25009d06c1c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pandemic_whistles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=33), nullable=False),
    sa.Column('facility_type', ENUM('hospital', 'extended_care', 'long_term_care', name='facilitytype'), nullable=False),
    sa.Column('district_state', sa.String(), nullable=False),
    sa.Column('district', sa.Integer(), nullable=False),
    sa.Column('reporter_type', ENUM('lpn', 'rn', 'cna', 'other', name='reportertype', create_type=False), nullable=False),
    sa.Column('reported_date', sa.DateTime(), nullable=False),
    sa.Column('surgical_masks', sa.Boolean(), nullable=False),
    sa.Column('n95_masks', sa.Boolean(), nullable=False),
    sa.Column('papr_hoods', sa.Boolean(), nullable=False),
    sa.Column('non_sterile_gloves', sa.Boolean(), nullable=False),
    sa.Column('isolation_gowns', sa.Boolean(), nullable=False),
    sa.Column('face_shields', sa.Boolean(), nullable=False),
    sa.Column('oxygen', sa.Boolean(), nullable=False),
    sa.Column('sedatives', sa.Boolean(), nullable=False),
    sa.Column('narcotic_analgesics', sa.Boolean(), nullable=False),
    sa.Column('paralytics', sa.Boolean(), nullable=False),
    sa.Column('icu_beds', sa.Boolean(), nullable=False),
    sa.Column('icu_trained_nurses', sa.Boolean(), nullable=False),
    sa.Column('ventilators', sa.Boolean(), nullable=False),
    sa.Column('test_none', sa.Boolean(), nullable=False),
    sa.Column('test_tried', sa.Boolean(), nullable=False),
    sa.Column('test_no_result', sa.Boolean(), nullable=False),
    sa.Column('test_swab_neg', sa.Boolean(), nullable=False),
    sa.Column('test_swab_pos', sa.Boolean(), nullable=False),
    sa.Column('test_anti_neg', sa.Boolean(), nullable=False),
    sa.Column('test_anti_pos', sa.Boolean(), nullable=False),
    sa.Column('willing_to_report', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pandemic_whistles')
    # ### end Alembic commands ###
